<?php

namespace App\Command;

use App\Entity\AdminUser;
use App\Entity\SoftwareVersion;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\Console\Attribute\AsCommand;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\Style\SymfonyStyle;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;

#[AsCommand(name: 'app:seed-data', description: 'Seed the database with all existing software versions and a default admin user')]
class SeedDataCommand extends Command
{
    public function __construct(
        private EntityManagerInterface $em,
        private UserPasswordHasherInterface $passwordHasher,
    ) {
        parent::__construct();
    }

    protected function execute(InputInterface $input, OutputInterface $output): int
    {
        $io = new SymfonyStyle($input, $output);

        // Create default admin user
        $existingAdmin = $this->em->getRepository(AdminUser::class)->findOneBy(['email' => 'admin@bimmer-tech.net']);
        if (!$existingAdmin) {
            $admin = new AdminUser();
            $admin->setEmail('admin@bimmer-tech.net');
            $admin->setRoles(['ROLE_ADMIN']);
            $admin->setPassword($this->passwordHasher->hashPassword($admin, 'admin123'));
            $this->em->persist($admin);
            $io->info('Created default admin user: admin@bimmer-tech.net / admin123');
        } else {
            $io->info('Admin user already exists, skipping.');
        }

        // Check if software versions already exist
        $count = $this->em->getRepository(SoftwareVersion::class)->count([]);
        if ($count > 0) {
            $io->info("$count software versions already exist, skipping seed.");
            $this->em->flush();
            $io->success('Seed complete.');
            return Command::SUCCESS;
        }

        $versions = $this->getSoftwareVersions();

        foreach ($versions as $v) {
            $sv = new SoftwareVersion();
            $sv->setName($v['name']);
            $sv->setSystemVersion($v['system_version']);
            $sv->setSystemVersionAlt($v['system_version_alt']);
            $sv->setLink($v['link'] ?: null);
            $sv->setStLink($v['st'] ?: null);
            $sv->setGdLink($v['gd'] ?: null);
            $sv->setLatest($v['latest']);
            $this->em->persist($sv);
        }

        $this->em->flush();
        $io->success(sprintf('Seeded %d software versions.', count($versions)));

        return Command::SUCCESS;
    }

    private function getSoftwareVersions(): array
    {
        return [
            // ========== MMI Prime CIC (ST only) ==========
            ['name' => 'MMI Prime CIC', 'system_version' => 'v3.1.1.2.mmi.c', 'system_version_alt' => '3.1.1.2.mmi.c', 'link' => 'https://drive.google.com/drive/folders/1SRkHReNFxeAl6mXzOiwyXcdv9CIdPWyE', 'st' => 'https://drive.google.com/drive/folders/1wXfribAWWliCvUMQEtdDrnki3he9EKCK', 'gd' => '', 'latest' => false],
            ['name' => 'MMI Prime CIC', 'system_version' => 'v3.1.1.4.mmi.c', 'system_version_alt' => '3.1.1.4.mmi.c', 'link' => 'https://drive.google.com/drive/folders/1SRkHReNFxeAl6mXzOiwyXcdv9CIdPWyE', 'st' => 'https://drive.google.com/drive/folders/1wXfribAWWliCvUMQEtdDrnki3he9EKCK', 'gd' => '', 'latest' => false],
            ['name' => 'MMI Prime CIC', 'system_version' => 'v3.1.1.4t.mmi.c', 'system_version_alt' => '3.1.1.4t.mmi.c', 'link' => 'https://drive.google.com/drive/folders/1SRkHReNFxeAl6mXzOiwyXcdv9CIdPWyE', 'st' => 'https://drive.google.com/drive/folders/1wXfribAWWliCvUMQEtdDrnki3he9EKCK', 'gd' => '', 'latest' => false],
            ['name' => 'MMI Prime CIC', 'system_version' => 'v3.1.1.5t.mmi.c', 'system_version_alt' => '3.1.1.5t.mmi.c', 'link' => 'https://drive.google.com/drive/folders/1SRkHReNFxeAl6mXzOiwyXcdv9CIdPWyE', 'st' => 'https://drive.google.com/drive/folders/1wXfribAWWliCvUMQEtdDrnki3he9EKCK', 'gd' => '', 'latest' => false],
            ['name' => 'MMI Prime CIC', 'system_version' => 'v3.1.1.6s.mmi.c', 'system_version_alt' => '3.1.1.6s.mmi.c', 'link' => 'https://drive.google.com/drive/folders/1SRkHReNFxeAl6mXzOiwyXcdv9CIdPWyE', 'st' => 'https://drive.google.com/drive/folders/1wXfribAWWliCvUMQEtdDrnki3he9EKCK', 'gd' => '', 'latest' => false],
            ['name' => 'MMI Prime CIC', 'system_version' => 'v3.1.1.7.mmi.c', 'system_version_alt' => '3.1.1.7.mmi.c', 'link' => 'https://drive.google.com/drive/folders/1SRkHReNFxeAl6mXzOiwyXcdv9CIdPWyE', 'st' => 'https://drive.google.com/drive/folders/1wXfribAWWliCvUMQEtdDrnki3he9EKCK', 'gd' => '', 'latest' => false],
            ['name' => 'MMI Prime CIC', 'system_version' => 'v3.1.1.7R4.mmi.c', 'system_version_alt' => '3.1.1.7R4.mmi.c', 'link' => 'https://drive.google.com/drive/folders/1SRkHReNFxeAl6mXzOiwyXcdv9CIdPWyE', 'st' => 'https://drive.google.com/drive/folders/1wXfribAWWliCvUMQEtdDrnki3he9EKCK', 'gd' => '', 'latest' => false],
            ['name' => 'MMI Prime CIC', 'system_version' => 'v3.1.1.8.mmi.c', 'system_version_alt' => '3.1.1.8.mmi.c', 'link' => 'https://drive.google.com/drive/folders/1SRkHReNFxeAl6mXzOiwyXcdv9CIdPWyE', 'st' => 'https://drive.google.com/drive/folders/1wXfribAWWliCvUMQEtdDrnki3he9EKCK', 'gd' => '', 'latest' => false],
            ['name' => 'MMI Prime CIC', 'system_version' => 'v3.1.1.8R4.mmi.c', 'system_version_alt' => '3.1.1.8R4.mmi.c', 'link' => 'https://drive.google.com/drive/folders/1SRkHReNFxeAl6mXzOiwyXcdv9CIdPWyE', 'st' => 'https://drive.google.com/drive/folders/1wXfribAWWliCvUMQEtdDrnki3he9EKCK', 'gd' => '', 'latest' => false],
            ['name' => 'MMI Prime CIC', 'system_version' => 'v3.1.1.9.mmipri.c', 'system_version_alt' => '3.1.1.9.mmipri.c', 'link' => 'https://drive.google.com/drive/folders/1SRkHReNFxeAl6mXzOiwyXcdv9CIdPWyE', 'st' => 'https://drive.google.com/drive/folders/1wXfribAWWliCvUMQEtdDrnki3he9EKCK', 'gd' => '', 'latest' => false],
            ['name' => 'MMI Prime CIC', 'system_version' => 'v3.2.0.mmipri.c', 'system_version_alt' => '3.2.0.mmipri.c', 'link' => 'https://drive.google.com/drive/folders/1SRkHReNFxeAl6mXzOiwyXcdv9CIdPWyE', 'st' => 'https://drive.google.com/drive/folders/1wXfribAWWliCvUMQEtdDrnki3he9EKCK', 'gd' => '', 'latest' => false],
            ['name' => 'MMI Prime CIC', 'system_version' => 'v3.3.0.mmipri.c', 'system_version_alt' => '3.3.0.mmipri.c', 'link' => 'https://drive.google.com/drive/folders/1SRkHReNFxeAl6mXzOiwyXcdv9CIdPWyE', 'st' => 'https://drive.google.com/drive/folders/1wXfribAWWliCvUMQEtdDrnki3he9EKCK', 'gd' => '', 'latest' => false],
            ['name' => 'MMI Prime CIC', 'system_version' => 'v3.3.1.mmipri.c', 'system_version_alt' => '3.3.1.mmipri.c', 'link' => 'https://drive.google.com/drive/folders/1SRkHReNFxeAl6mXzOiwyXcdv9CIdPWyE', 'st' => 'https://drive.google.com/drive/folders/1wXfribAWWliCvUMQEtdDrnki3he9EKCK', 'gd' => '', 'latest' => false],
            ['name' => 'MMI Prime CIC', 'system_version' => 'v3.3.2.mmipri.c', 'system_version_alt' => '3.3.2.mmipri.c', 'link' => 'https://drive.google.com/drive/folders/1SRkHReNFxeAl6mXzOiwyXcdv9CIdPWyE', 'st' => 'https://drive.google.com/drive/folders/1wXfribAWWliCvUMQEtdDrnki3he9EKCK', 'gd' => '', 'latest' => false],
            ['name' => 'MMI Prime CIC', 'system_version' => 'v3.3.3.mmipri.c', 'system_version_alt' => '3.3.3.mmipri.c', 'link' => 'https://drive.google.com/drive/folders/1SRkHReNFxeAl6mXzOiwyXcdv9CIdPWyE', 'st' => 'https://drive.google.com/drive/folders/1wXfribAWWliCvUMQEtdDrnki3he9EKCK', 'gd' => '', 'latest' => false],
            ['name' => 'MMI Prime CIC', 'system_version' => 'v3.3.4.mmipri.c', 'system_version_alt' => '3.3.4.mmipri.c', 'link' => 'https://drive.google.com/drive/folders/1SRkHReNFxeAl6mXzOiwyXcdv9CIdPWyE', 'st' => 'https://drive.google.com/drive/folders/1wXfribAWWliCvUMQEtdDrnki3he9EKCK', 'gd' => '', 'latest' => false],
            ['name' => 'MMI Prime CIC', 'system_version' => 'v3.3.5.mmipri.c', 'system_version_alt' => '3.3.5.mmipri.c', 'link' => 'https://drive.google.com/drive/folders/1SRkHReNFxeAl6mXzOiwyXcdv9CIdPWyE', 'st' => 'https://drive.google.com/drive/folders/1wXfribAWWliCvUMQEtdDrnki3he9EKCK', 'gd' => '', 'latest' => false],
            ['name' => 'MMI Prime CIC', 'system_version' => 'v3.3.6.mmipri.c', 'system_version_alt' => '3.3.6.mmipri.c', 'link' => 'https://drive.google.com/drive/folders/1SRkHReNFxeAl6mXzOiwyXcdv9CIdPWyE', 'st' => 'https://drive.google.com/drive/folders/1wXfribAWWliCvUMQEtdDrnki3he9EKCK', 'gd' => '', 'latest' => false],
            ['name' => 'MMI Prime CIC', 'system_version' => 'v3.3.7.mmipri.c', 'system_version_alt' => '3.3.7.mmipri.c', 'link' => 'https://drive.google.com/drive/folders/1SRkHReNFxeAl6mXzOiwyXcdv9CIdPWyE', 'st' => '', 'gd' => '', 'latest' => true],

            // ========== MMI Prime NBT (ST + GD) ==========
            ['name' => 'MMI Prime NBT', 'system_version' => 'v3.1.1.4.mmi.b', 'system_version_alt' => '3.1.1.4.mmi.b', 'link' => 'https://drive.google.com/drive/folders/1PyoGrao0HT1Nh9RIlYiEoYIODF9xgoJL', 'st' => 'https://drive.google.com/drive/folders/1Bk3ZdyrpsWRT0R3fN7jCYEhnRT1YcEYg', 'gd' => 'https://drive.google.com/drive/folders/1Rv6pVyo2qy0rAIkEVUFJwyItWsRLuiuE', 'latest' => false],
            ['name' => 'MMI Prime NBT', 'system_version' => 'v3.1.1.4t.mmi.b', 'system_version_alt' => '3.1.1.4t.mmi.b', 'link' => 'https://drive.google.com/drive/folders/1PyoGrao0HT1Nh9RIlYiEoYIODF9xgoJL', 'st' => 'https://drive.google.com/drive/folders/1Bk3ZdyrpsWRT0R3fN7jCYEhnRT1YcEYg', 'gd' => 'https://drive.google.com/drive/folders/1Rv6pVyo2qy0rAIkEVUFJwyItWsRLuiuE', 'latest' => false],
            ['name' => 'MMI Prime NBT', 'system_version' => 'v3.1.1.5t.mmi.b', 'system_version_alt' => '3.1.1.5t.mmi.b', 'link' => 'https://drive.google.com/drive/folders/1PyoGrao0HT1Nh9RIlYiEoYIODF9xgoJL', 'st' => 'https://drive.google.com/drive/folders/1Bk3ZdyrpsWRT0R3fN7jCYEhnRT1YcEYg', 'gd' => 'https://drive.google.com/drive/folders/1Rv6pVyo2qy0rAIkEVUFJwyItWsRLuiuE', 'latest' => false],
            ['name' => 'MMI Prime NBT', 'system_version' => 'v3.1.1.5t4.mmi.b', 'system_version_alt' => '3.1.1.5t4.mmi.b', 'link' => 'https://drive.google.com/drive/folders/1PyoGrao0HT1Nh9RIlYiEoYIODF9xgoJL', 'st' => 'https://drive.google.com/drive/folders/1Bk3ZdyrpsWRT0R3fN7jCYEhnRT1YcEYg', 'gd' => 'https://drive.google.com/drive/folders/1Rv6pVyo2qy0rAIkEVUFJwyItWsRLuiuE', 'latest' => false],
            ['name' => 'MMI Prime NBT', 'system_version' => 'v3.1.1.6s.mmi.b', 'system_version_alt' => '3.1.1.6s.mmi.b', 'link' => 'https://drive.google.com/drive/folders/1PyoGrao0HT1Nh9RIlYiEoYIODF9xgoJL', 'st' => 'https://drive.google.com/drive/folders/1Bk3ZdyrpsWRT0R3fN7jCYEhnRT1YcEYg', 'gd' => 'https://drive.google.com/drive/folders/1Rv6pVyo2qy0rAIkEVUFJwyItWsRLuiuE', 'latest' => false],
            ['name' => 'MMI Prime NBT', 'system_version' => 'v3.1.1.7.mmi.b', 'system_version_alt' => '3.1.1.7.mmi.b', 'link' => 'https://drive.google.com/drive/folders/1PyoGrao0HT1Nh9RIlYiEoYIODF9xgoJL', 'st' => 'https://drive.google.com/drive/folders/1Bk3ZdyrpsWRT0R3fN7jCYEhnRT1YcEYg', 'gd' => 'https://drive.google.com/drive/folders/1Rv6pVyo2qy0rAIkEVUFJwyItWsRLuiuE', 'latest' => false],
            ['name' => 'MMI Prime NBT', 'system_version' => 'v3.1.1.7R4.mmi.b', 'system_version_alt' => '3.1.1.7R4.mmi.b', 'link' => 'https://drive.google.com/drive/folders/1PyoGrao0HT1Nh9RIlYiEoYIODF9xgoJL', 'st' => 'https://drive.google.com/drive/folders/1Bk3ZdyrpsWRT0R3fN7jCYEhnRT1YcEYg', 'gd' => 'https://drive.google.com/drive/folders/1Rv6pVyo2qy0rAIkEVUFJwyItWsRLuiuE', 'latest' => false],
            ['name' => 'MMI Prime NBT', 'system_version' => 'v3.1.1.8.mmi.b', 'system_version_alt' => '3.1.1.8.mmi.b', 'link' => 'https://drive.google.com/drive/folders/1PyoGrao0HT1Nh9RIlYiEoYIODF9xgoJL', 'st' => 'https://drive.google.com/drive/folders/1Bk3ZdyrpsWRT0R3fN7jCYEhnRT1YcEYg', 'gd' => 'https://drive.google.com/drive/folders/1Rv6pVyo2qy0rAIkEVUFJwyItWsRLuiuE', 'latest' => false],
            ['name' => 'MMI Prime NBT', 'system_version' => 'v3.1.1.8R4.mmi.b', 'system_version_alt' => '3.1.1.8R4.mmi.b', 'link' => 'https://drive.google.com/drive/folders/1PyoGrao0HT1Nh9RIlYiEoYIODF9xgoJL', 'st' => 'https://drive.google.com/drive/folders/1Bk3ZdyrpsWRT0R3fN7jCYEhnRT1YcEYg', 'gd' => 'https://drive.google.com/drive/folders/1Rv6pVyo2qy0rAIkEVUFJwyItWsRLuiuE', 'latest' => false],
            ['name' => 'MMI Prime NBT', 'system_version' => 'v3.1.1.9.mmipri.b', 'system_version_alt' => '3.1.1.9.mmipri.b', 'link' => 'https://drive.google.com/drive/folders/1PyoGrao0HT1Nh9RIlYiEoYIODF9xgoJL', 'st' => 'https://drive.google.com/drive/folders/1Bk3ZdyrpsWRT0R3fN7jCYEhnRT1YcEYg', 'gd' => 'https://drive.google.com/drive/folders/1Rv6pVyo2qy0rAIkEVUFJwyItWsRLuiuE', 'latest' => false],
            ['name' => 'MMI Prime NBT', 'system_version' => 'v3.2.0.mmipri.b', 'system_version_alt' => '3.2.0.mmipri.b', 'link' => 'https://drive.google.com/drive/folders/1PyoGrao0HT1Nh9RIlYiEoYIODF9xgoJL', 'st' => 'https://drive.google.com/drive/folders/1Bk3ZdyrpsWRT0R3fN7jCYEhnRT1YcEYg', 'gd' => 'https://drive.google.com/drive/folders/1Rv6pVyo2qy0rAIkEVUFJwyItWsRLuiuE', 'latest' => false],
            ['name' => 'MMI Prime NBT', 'system_version' => 'v3.3.0.mmipri.b', 'system_version_alt' => '3.3.0.mmipri.b', 'link' => 'https://drive.google.com/drive/folders/1PyoGrao0HT1Nh9RIlYiEoYIODF9xgoJL', 'st' => 'https://drive.google.com/drive/folders/1Bk3ZdyrpsWRT0R3fN7jCYEhnRT1YcEYg', 'gd' => 'https://drive.google.com/drive/folders/1Rv6pVyo2qy0rAIkEVUFJwyItWsRLuiuE', 'latest' => false],
            ['name' => 'MMI Prime NBT', 'system_version' => 'v3.3.1.mmipri.b', 'system_version_alt' => '3.3.1.mmipri.b', 'link' => 'https://drive.google.com/drive/folders/1PyoGrao0HT1Nh9RIlYiEoYIODF9xgoJL', 'st' => 'https://drive.google.com/drive/folders/1Bk3ZdyrpsWRT0R3fN7jCYEhnRT1YcEYg', 'gd' => 'https://drive.google.com/drive/folders/1Rv6pVyo2qy0rAIkEVUFJwyItWsRLuiuE', 'latest' => false],
            ['name' => 'MMI Prime NBT', 'system_version' => 'v3.3.2.mmipri.b', 'system_version_alt' => '3.3.2.mmipri.b', 'link' => 'https://drive.google.com/drive/folders/1PyoGrao0HT1Nh9RIlYiEoYIODF9xgoJL', 'st' => 'https://drive.google.com/drive/folders/1Bk3ZdyrpsWRT0R3fN7jCYEhnRT1YcEYg', 'gd' => 'https://drive.google.com/drive/folders/1Rv6pVyo2qy0rAIkEVUFJwyItWsRLuiuE', 'latest' => false],
            ['name' => 'MMI Prime NBT', 'system_version' => 'v3.3.3.mmipri.b', 'system_version_alt' => '3.3.3.mmipri.b', 'link' => 'https://drive.google.com/drive/folders/1PyoGrao0HT1Nh9RIlYiEoYIODF9xgoJL', 'st' => 'https://drive.google.com/drive/folders/1Bk3ZdyrpsWRT0R3fN7jCYEhnRT1YcEYg', 'gd' => 'https://drive.google.com/drive/folders/1Rv6pVyo2qy0rAIkEVUFJwyItWsRLuiuE', 'latest' => false],
            ['name' => 'MMI Prime NBT', 'system_version' => 'v3.3.4.mmipri.b', 'system_version_alt' => '3.3.4.mmipri.b', 'link' => 'https://drive.google.com/drive/folders/1PyoGrao0HT1Nh9RIlYiEoYIODF9xgoJL', 'st' => 'https://drive.google.com/drive/folders/1Bk3ZdyrpsWRT0R3fN7jCYEhnRT1YcEYg', 'gd' => 'https://drive.google.com/drive/folders/1Rv6pVyo2qy0rAIkEVUFJwyItWsRLuiuE', 'latest' => false],
            ['name' => 'MMI Prime NBT', 'system_version' => 'v3.3.5.mmipri.b', 'system_version_alt' => '3.3.5.mmipri.b', 'link' => 'https://drive.google.com/drive/folders/1PyoGrao0HT1Nh9RIlYiEoYIODF9xgoJL', 'st' => 'https://drive.google.com/drive/folders/1Bk3ZdyrpsWRT0R3fN7jCYEhnRT1YcEYg', 'gd' => 'https://drive.google.com/drive/folders/1Rv6pVyo2qy0rAIkEVUFJwyItWsRLuiuE', 'latest' => false],
            ['name' => 'MMI Prime NBT', 'system_version' => 'v3.3.6.mmipri.b', 'system_version_alt' => '3.3.6.mmipri.b', 'link' => 'https://drive.google.com/drive/folders/1PyoGrao0HT1Nh9RIlYiEoYIODF9xgoJL', 'st' => 'https://drive.google.com/drive/folders/1Bk3ZdyrpsWRT0R3fN7jCYEhnRT1YcEYg', 'gd' => 'https://drive.google.com/drive/folders/1Rv6pVyo2qy0rAIkEVUFJwyItWsRLuiuE', 'latest' => false],
            ['name' => 'MMI Prime NBT', 'system_version' => 'v3.3.7.mmipri.b', 'system_version_alt' => '3.3.7.mmipri.b', 'link' => 'https://drive.google.com/drive/folders/1PyoGrao0HT1Nh9RIlYiEoYIODF9xgoJL', 'st' => '', 'gd' => '', 'latest' => true],

            // ========== MMI Prime EVO (ST + GD) ==========
            ['name' => 'MMI Prime EVO', 'system_version' => 'v3.1.1.2.mmi.e', 'system_version_alt' => '3.1.1.2.mmi.e', 'link' => 'https://drive.google.com/drive/folders/1F8hm9jIN9vPwxEv2Dqk9ABBxZoqrSQyS', 'st' => 'https://drive.google.com/drive/folders/1B6xGokuf5pzV1Y4qZBYlcQ-8uK99Yfff', 'gd' => 'https://drive.google.com/drive/folders/1L7Uj4H4La8OMguKGtI0M0b4_DZcFqDlU', 'latest' => false],
            ['name' => 'MMI Prime EVO', 'system_version' => 'v3.1.1.4.mmi.e', 'system_version_alt' => '3.1.1.4.mmi.e', 'link' => 'https://drive.google.com/drive/folders/1F8hm9jIN9vPwxEv2Dqk9ABBxZoqrSQyS', 'st' => 'https://drive.google.com/drive/folders/1B6xGokuf5pzV1Y4qZBYlcQ-8uK99Yfff', 'gd' => 'https://drive.google.com/drive/folders/1L7Uj4H4La8OMguKGtI0M0b4_DZcFqDlU', 'latest' => false],
            ['name' => 'MMI Prime EVO', 'system_version' => 'v3.1.1.4t1.mmi.e', 'system_version_alt' => '3.1.1.4t1.mmi.e', 'link' => 'https://drive.google.com/drive/folders/1F8hm9jIN9vPwxEv2Dqk9ABBxZoqrSQyS', 'st' => 'https://drive.google.com/drive/folders/1B6xGokuf5pzV1Y4qZBYlcQ-8uK99Yfff', 'gd' => 'https://drive.google.com/drive/folders/1L7Uj4H4La8OMguKGtI0M0b4_DZcFqDlU', 'latest' => false],
            ['name' => 'MMI Prime EVO', 'system_version' => 'v3.1.1.5t.mmi.e', 'system_version_alt' => '3.1.1.5t.mmi.e', 'link' => 'https://drive.google.com/drive/folders/1F8hm9jIN9vPwxEv2Dqk9ABBxZoqrSQyS', 'st' => 'https://drive.google.com/drive/folders/1B6xGokuf5pzV1Y4qZBYlcQ-8uK99Yfff', 'gd' => 'https://drive.google.com/drive/folders/1L7Uj4H4La8OMguKGtI0M0b4_DZcFqDlU', 'latest' => false],
            ['name' => 'MMI Prime EVO', 'system_version' => 'v3.1.1.6.mmi.e', 'system_version_alt' => '3.1.1.6.mmi.e', 'link' => 'https://drive.google.com/drive/folders/1F8hm9jIN9vPwxEv2Dqk9ABBxZoqrSQyS', 'st' => 'https://drive.google.com/drive/folders/1B6xGokuf5pzV1Y4qZBYlcQ-8uK99Yfff', 'gd' => 'https://drive.google.com/drive/folders/1L7Uj4H4La8OMguKGtI0M0b4_DZcFqDlU', 'latest' => false],
            ['name' => 'MMI Prime EVO', 'system_version' => 'v3.1.1.6s.mmi.e', 'system_version_alt' => '3.1.1.6s.mmi.e', 'link' => 'https://drive.google.com/drive/folders/1F8hm9jIN9vPwxEv2Dqk9ABBxZoqrSQyS', 'st' => 'https://drive.google.com/drive/folders/1B6xGokuf5pzV1Y4qZBYlcQ-8uK99Yfff', 'gd' => 'https://drive.google.com/drive/folders/1L7Uj4H4La8OMguKGtI0M0b4_DZcFqDlU', 'latest' => false],
            ['name' => 'MMI Prime EVO', 'system_version' => 'v3.1.1.7.mmi.e', 'system_version_alt' => '3.1.1.7.mmi.e', 'link' => 'https://drive.google.com/drive/folders/1F8hm9jIN9vPwxEv2Dqk9ABBxZoqrSQyS', 'st' => 'https://drive.google.com/drive/folders/1B6xGokuf5pzV1Y4qZBYlcQ-8uK99Yfff', 'gd' => 'https://drive.google.com/drive/folders/1L7Uj4H4La8OMguKGtI0M0b4_DZcFqDlU', 'latest' => false],
            ['name' => 'MMI Prime EVO', 'system_version' => 'v3.1.1.7R4.mmi.e', 'system_version_alt' => '3.1.1.7R4.mmi.e', 'link' => 'https://drive.google.com/drive/folders/1F8hm9jIN9vPwxEv2Dqk9ABBxZoqrSQyS', 'st' => 'https://drive.google.com/drive/folders/1B6xGokuf5pzV1Y4qZBYlcQ-8uK99Yfff', 'gd' => 'https://drive.google.com/drive/folders/1L7Uj4H4La8OMguKGtI0M0b4_DZcFqDlU', 'latest' => false],
            ['name' => 'MMI Prime EVO', 'system_version' => 'v3.1.1.8.mmi.e', 'system_version_alt' => '3.1.1.8.mmi.e', 'link' => 'https://drive.google.com/drive/folders/1F8hm9jIN9vPwxEv2Dqk9ABBxZoqrSQyS', 'st' => 'https://drive.google.com/drive/folders/1B6xGokuf5pzV1Y4qZBYlcQ-8uK99Yfff', 'gd' => 'https://drive.google.com/drive/folders/1L7Uj4H4La8OMguKGtI0M0b4_DZcFqDlU', 'latest' => false],
            ['name' => 'MMI Prime EVO', 'system_version' => 'v3.1.1.8R4.mmi.e', 'system_version_alt' => '3.1.1.8R4.mmi.e', 'link' => 'https://drive.google.com/drive/folders/1F8hm9jIN9vPwxEv2Dqk9ABBxZoqrSQyS', 'st' => 'https://drive.google.com/drive/folders/1B6xGokuf5pzV1Y4qZBYlcQ-8uK99Yfff', 'gd' => 'https://drive.google.com/drive/folders/1L7Uj4H4La8OMguKGtI0M0b4_DZcFqDlU', 'latest' => false],
            ['name' => 'MMI Prime EVO', 'system_version' => 'v3.1.1.9.mmipri.e', 'system_version_alt' => '3.1.1.9.mmipri.e', 'link' => 'https://drive.google.com/drive/folders/1F8hm9jIN9vPwxEv2Dqk9ABBxZoqrSQyS', 'st' => 'https://drive.google.com/drive/folders/1B6xGokuf5pzV1Y4qZBYlcQ-8uK99Yfff', 'gd' => 'https://drive.google.com/drive/folders/1L7Uj4H4La8OMguKGtI0M0b4_DZcFqDlU', 'latest' => false],
            ['name' => 'MMI Prime EVO', 'system_version' => 'v3.2.0.mmipri.e', 'system_version_alt' => '3.2.0.mmipri.e', 'link' => 'https://drive.google.com/drive/folders/1F8hm9jIN9vPwxEv2Dqk9ABBxZoqrSQyS', 'st' => 'https://drive.google.com/drive/folders/1B6xGokuf5pzV1Y4qZBYlcQ-8uK99Yfff', 'gd' => 'https://drive.google.com/drive/folders/1L7Uj4H4La8OMguKGtI0M0b4_DZcFqDlU', 'latest' => false],
            ['name' => 'MMI Prime EVO', 'system_version' => 'v3.3.0.mmipri.e', 'system_version_alt' => '3.3.0.mmipri.e', 'link' => 'https://drive.google.com/drive/folders/1F8hm9jIN9vPwxEv2Dqk9ABBxZoqrSQyS', 'st' => 'https://drive.google.com/drive/folders/1B6xGokuf5pzV1Y4qZBYlcQ-8uK99Yfff', 'gd' => 'https://drive.google.com/drive/folders/1L7Uj4H4La8OMguKGtI0M0b4_DZcFqDlU', 'latest' => false],
            ['name' => 'MMI Prime EVO', 'system_version' => 'v3.3.1.mmipri.e', 'system_version_alt' => '3.3.1.mmipri.e', 'link' => 'https://drive.google.com/drive/folders/1F8hm9jIN9vPwxEv2Dqk9ABBxZoqrSQyS', 'st' => 'https://drive.google.com/drive/folders/1B6xGokuf5pzV1Y4qZBYlcQ-8uK99Yfff', 'gd' => 'https://drive.google.com/drive/folders/1L7Uj4H4La8OMguKGtI0M0b4_DZcFqDlU', 'latest' => false],
            ['name' => 'MMI Prime EVO', 'system_version' => 'v3.3.2.mmipri.e', 'system_version_alt' => '3.3.2.mmipri.e', 'link' => 'https://drive.google.com/drive/folders/1F8hm9jIN9vPwxEv2Dqk9ABBxZoqrSQyS', 'st' => 'https://drive.google.com/drive/folders/1B6xGokuf5pzV1Y4qZBYlcQ-8uK99Yfff', 'gd' => 'https://drive.google.com/drive/folders/1L7Uj4H4La8OMguKGtI0M0b4_DZcFqDlU', 'latest' => false],
            ['name' => 'MMI Prime EVO', 'system_version' => 'v3.3.3.mmipri.e', 'system_version_alt' => '3.3.3.mmipri.e', 'link' => 'https://drive.google.com/drive/folders/1F8hm9jIN9vPwxEv2Dqk9ABBxZoqrSQyS', 'st' => 'https://drive.google.com/drive/folders/1B6xGokuf5pzV1Y4qZBYlcQ-8uK99Yfff', 'gd' => 'https://drive.google.com/drive/folders/1L7Uj4H4La8OMguKGtI0M0b4_DZcFqDlU', 'latest' => false],
            ['name' => 'MMI Prime EVO', 'system_version' => 'v3.3.4.mmipri.e', 'system_version_alt' => '3.3.4.mmipri.e', 'link' => 'https://drive.google.com/drive/folders/1F8hm9jIN9vPwxEv2Dqk9ABBxZoqrSQyS', 'st' => 'https://drive.google.com/drive/folders/1B6xGokuf5pzV1Y4qZBYlcQ-8uK99Yfff', 'gd' => 'https://drive.google.com/drive/folders/1L7Uj4H4La8OMguKGtI0M0b4_DZcFqDlU', 'latest' => false],
            ['name' => 'MMI Prime EVO', 'system_version' => 'v3.3.5.mmipri.e', 'system_version_alt' => '3.3.5.mmipri.e', 'link' => 'https://drive.google.com/drive/folders/1F8hm9jIN9vPwxEv2Dqk9ABBxZoqrSQyS', 'st' => 'https://drive.google.com/drive/folders/1B6xGokuf5pzV1Y4qZBYlcQ-8uK99Yfff', 'gd' => 'https://drive.google.com/drive/folders/1L7Uj4H4La8OMguKGtI0M0b4_DZcFqDlU', 'latest' => false],
            ['name' => 'MMI Prime EVO', 'system_version' => 'v3.3.6.mmipri.e', 'system_version_alt' => '3.3.6.mmipri.e', 'link' => 'https://drive.google.com/drive/folders/1F8hm9jIN9vPwxEv2Dqk9ABBxZoqrSQyS', 'st' => 'https://drive.google.com/drive/folders/1B6xGokuf5pzV1Y4qZBYlcQ-8uK99Yfff', 'gd' => 'https://drive.google.com/drive/folders/1L7Uj4H4La8OMguKGtI0M0b4_DZcFqDlU', 'latest' => false],
            ['name' => 'MMI Prime EVO', 'system_version' => 'v3.3.7.mmipri.e', 'system_version_alt' => '3.3.7.mmipri.e', 'link' => 'https://drive.google.com/drive/folders/1F8hm9jIN9vPwxEv2Dqk9ABBxZoqrSQyS', 'st' => '', 'gd' => '', 'latest' => true],

            // ========== MMI PRO CIC (ST only) ==========
            ['name' => 'MMI PRO CIC', 'system_version' => 'v3.1.1.8R1.mmipro.c', 'system_version_alt' => '3.1.1.8R1.mmipro.c', 'link' => 'https://drive.google.com/drive/folders/1CGC4iZoX2uvuiMUsA7AYp8n6roc602jJ', 'st' => 'https://drive.google.com/drive/folders/1tP5HBhEgZnS4e8boX4MNut1ZZMtObfwD', 'gd' => '', 'latest' => false],
            ['name' => 'MMI PRO CIC', 'system_version' => 'v3.1.1.8R3.mmipro.c', 'system_version_alt' => '3.1.1.8R3.mmipro.c', 'link' => 'https://drive.google.com/drive/folders/1CGC4iZoX2uvuiMUsA7AYp8n6roc602jJ', 'st' => 'https://drive.google.com/drive/folders/1tP5HBhEgZnS4e8boX4MNut1ZZMtObfwD', 'gd' => '', 'latest' => false],
            ['name' => 'MMI PRO CIC', 'system_version' => 'v3.1.1.8R4.mmipro.c', 'system_version_alt' => '3.1.1.8R4.mmipro.c', 'link' => 'https://drive.google.com/drive/folders/1CGC4iZoX2uvuiMUsA7AYp8n6roc602jJ', 'st' => 'https://drive.google.com/drive/folders/1tP5HBhEgZnS4e8boX4MNut1ZZMtObfwD', 'gd' => '', 'latest' => false],
            ['name' => 'MMI PRO CIC', 'system_version' => 'v3.1.1.9.mmipro.c', 'system_version_alt' => '3.1.1.9.mmipro.c', 'link' => 'https://drive.google.com/drive/folders/1CGC4iZoX2uvuiMUsA7AYp8n6roc602jJ', 'st' => 'https://drive.google.com/drive/folders/1tP5HBhEgZnS4e8boX4MNut1ZZMtObfwD', 'gd' => '', 'latest' => false],
            ['name' => 'MMI PRO CIC', 'system_version' => 'v3.2.0.mmipro.c', 'system_version_alt' => '3.2.0.mmipro.c', 'link' => 'https://drive.google.com/drive/folders/1CGC4iZoX2uvuiMUsA7AYp8n6roc602jJ', 'st' => 'https://drive.google.com/drive/folders/1tP5HBhEgZnS4e8boX4MNut1ZZMtObfwD', 'gd' => '', 'latest' => false],
            ['name' => 'MMI PRO CIC', 'system_version' => 'v3.3.0.mmipro.c', 'system_version_alt' => '3.3.0.mmipro.c', 'link' => 'https://drive.google.com/drive/folders/1CGC4iZoX2uvuiMUsA7AYp8n6roc602jJ', 'st' => 'https://drive.google.com/drive/folders/1tP5HBhEgZnS4e8boX4MNut1ZZMtObfwD', 'gd' => '', 'latest' => false],
            ['name' => 'MMI PRO CIC', 'system_version' => 'v3.3.1.mmipro.c', 'system_version_alt' => '3.3.1.mmipro.c', 'link' => 'https://drive.google.com/drive/folders/1CGC4iZoX2uvuiMUsA7AYp8n6roc602jJ', 'st' => 'https://drive.google.com/drive/folders/1tP5HBhEgZnS4e8boX4MNut1ZZMtObfwD', 'gd' => '', 'latest' => false],
            ['name' => 'MMI PRO CIC', 'system_version' => 'v3.3.2.mmipro.c', 'system_version_alt' => '3.3.2.mmipro.c', 'link' => 'https://drive.google.com/drive/folders/1CGC4iZoX2uvuiMUsA7AYp8n6roc602jJ', 'st' => 'https://drive.google.com/drive/folders/1tP5HBhEgZnS4e8boX4MNut1ZZMtObfwD', 'gd' => '', 'latest' => false],
            ['name' => 'MMI PRO CIC', 'system_version' => 'v3.3.3.mmipro.c', 'system_version_alt' => '3.3.3.mmipro.c', 'link' => 'https://drive.google.com/drive/folders/1CGC4iZoX2uvuiMUsA7AYp8n6roc602jJ', 'st' => 'https://drive.google.com/drive/folders/1tP5HBhEgZnS4e8boX4MNut1ZZMtObfwD', 'gd' => '', 'latest' => false],
            ['name' => 'MMI PRO CIC', 'system_version' => 'v3.3.4.mmipro.c', 'system_version_alt' => '3.3.4.mmipro.c', 'link' => 'https://drive.google.com/drive/folders/1CGC4iZoX2uvuiMUsA7AYp8n6roc602jJ', 'st' => 'https://drive.google.com/drive/folders/1tP5HBhEgZnS4e8boX4MNut1ZZMtObfwD', 'gd' => '', 'latest' => false],
            ['name' => 'MMI PRO CIC', 'system_version' => 'v3.3.5.mmipro.c', 'system_version_alt' => '3.3.5.mmipro.c', 'link' => 'https://drive.google.com/drive/folders/1CGC4iZoX2uvuiMUsA7AYp8n6roc602jJ', 'st' => 'https://drive.google.com/drive/folders/1tP5HBhEgZnS4e8boX4MNut1ZZMtObfwD', 'gd' => '', 'latest' => false],
            ['name' => 'MMI PRO CIC', 'system_version' => 'v3.3.6.mmipro.c', 'system_version_alt' => '3.3.6.mmipro.c', 'link' => 'https://drive.google.com/drive/folders/1CGC4iZoX2uvuiMUsA7AYp8n6roc602jJ', 'st' => 'https://drive.google.com/drive/folders/1tP5HBhEgZnS4e8boX4MNut1ZZMtObfwD', 'gd' => '', 'latest' => false],
            ['name' => 'MMI PRO CIC', 'system_version' => 'v3.3.7.mmipro.c', 'system_version_alt' => '3.3.7.mmipro.c', 'link' => 'https://drive.google.com/drive/folders/1CGC4iZoX2uvuiMUsA7AYp8n6roc602jJ', 'st' => '', 'gd' => '', 'latest' => true],

            // ========== MMI PRO NBT (ST + GD) ==========
            ['name' => 'MMI PRO NBT', 'system_version' => 'v3.1.1.8R1.mmipro.b', 'system_version_alt' => '3.1.1.8R1.mmipro.b', 'link' => 'https://drive.google.com/drive/folders/1gwe0Bmq5m1V0oSGjCWDzPIlkqc7dqm3f', 'st' => 'https://drive.google.com/drive/folders/1rCgqberGLDSj9yn2McHVDc-0ydphqHRw', 'gd' => 'https://drive.google.com/drive/folders/1bd61AefAypTICA2PFfJw_5Ly3RCSRkqh', 'latest' => false],
            ['name' => 'MMI PRO NBT', 'system_version' => 'v3.1.1.8R3.mmipro.b', 'system_version_alt' => '3.1.1.8R3.mmipro.b', 'link' => 'https://drive.google.com/drive/folders/1gwe0Bmq5m1V0oSGjCWDzPIlkqc7dqm3f', 'st' => 'https://drive.google.com/drive/folders/1rCgqberGLDSj9yn2McHVDc-0ydphqHRw', 'gd' => 'https://drive.google.com/drive/folders/1bd61AefAypTICA2PFfJw_5Ly3RCSRkqh', 'latest' => false],
            ['name' => 'MMI PRO NBT', 'system_version' => 'v3.1.1.8R4.mmipro.b', 'system_version_alt' => '3.1.1.8R4.mmipro.b', 'link' => 'https://drive.google.com/drive/folders/1gwe0Bmq5m1V0oSGjCWDzPIlkqc7dqm3f', 'st' => 'https://drive.google.com/drive/folders/1rCgqberGLDSj9yn2McHVDc-0ydphqHRw', 'gd' => 'https://drive.google.com/drive/folders/1bd61AefAypTICA2PFfJw_5Ly3RCSRkqh', 'latest' => false],
            ['name' => 'MMI PRO NBT', 'system_version' => 'v3.1.1.9.mmipro.b', 'system_version_alt' => '3.1.1.9.mmipro.b', 'link' => 'https://drive.google.com/drive/folders/1gwe0Bmq5m1V0oSGjCWDzPIlkqc7dqm3f', 'st' => 'https://drive.google.com/drive/folders/1rCgqberGLDSj9yn2McHVDc-0ydphqHRw', 'gd' => 'https://drive.google.com/drive/folders/1bd61AefAypTICA2PFfJw_5Ly3RCSRkqh', 'latest' => false],
            ['name' => 'MMI PRO NBT', 'system_version' => 'v3.2.0.mmipro.b', 'system_version_alt' => '3.2.0.mmipro.b', 'link' => 'https://drive.google.com/drive/folders/1gwe0Bmq5m1V0oSGjCWDzPIlkqc7dqm3f', 'st' => 'https://drive.google.com/drive/folders/1rCgqberGLDSj9yn2McHVDc-0ydphqHRw', 'gd' => 'https://drive.google.com/drive/folders/1bd61AefAypTICA2PFfJw_5Ly3RCSRkqh', 'latest' => false],
            ['name' => 'MMI PRO NBT', 'system_version' => 'v3.3.0.mmipro.b', 'system_version_alt' => '3.3.0.mmipro.b', 'link' => 'https://drive.google.com/drive/folders/1gwe0Bmq5m1V0oSGjCWDzPIlkqc7dqm3f', 'st' => 'https://drive.google.com/drive/folders/1rCgqberGLDSj9yn2McHVDc-0ydphqHRw', 'gd' => 'https://drive.google.com/drive/folders/1bd61AefAypTICA2PFfJw_5Ly3RCSRkqh', 'latest' => false],
            ['name' => 'MMI PRO NBT', 'system_version' => 'v3.3.1.mmipro.b', 'system_version_alt' => '3.3.1.mmipro.b', 'link' => 'https://drive.google.com/drive/folders/1gwe0Bmq5m1V0oSGjCWDzPIlkqc7dqm3f', 'st' => 'https://drive.google.com/drive/folders/1rCgqberGLDSj9yn2McHVDc-0ydphqHRw', 'gd' => 'https://drive.google.com/drive/folders/1bd61AefAypTICA2PFfJw_5Ly3RCSRkqh', 'latest' => false],
            ['name' => 'MMI PRO NBT', 'system_version' => 'v3.3.2.mmipro.b', 'system_version_alt' => '3.3.2.mmipro.b', 'link' => 'https://drive.google.com/drive/folders/1gwe0Bmq5m1V0oSGjCWDzPIlkqc7dqm3f', 'st' => 'https://drive.google.com/drive/folders/1rCgqberGLDSj9yn2McHVDc-0ydphqHRw', 'gd' => 'https://drive.google.com/drive/folders/1bd61AefAypTICA2PFfJw_5Ly3RCSRkqh', 'latest' => false],
            ['name' => 'MMI PRO NBT', 'system_version' => 'v3.3.3.mmipro.b', 'system_version_alt' => '3.3.3.mmipro.b', 'link' => 'https://drive.google.com/drive/folders/1gwe0Bmq5m1V0oSGjCWDzPIlkqc7dqm3f', 'st' => 'https://drive.google.com/drive/folders/1rCgqberGLDSj9yn2McHVDc-0ydphqHRw', 'gd' => 'https://drive.google.com/drive/folders/1bd61AefAypTICA2PFfJw_5Ly3RCSRkqh', 'latest' => false],
            ['name' => 'MMI PRO NBT', 'system_version' => 'v3.3.4.mmipro.b', 'system_version_alt' => '3.3.4.mmipro.b', 'link' => 'https://drive.google.com/drive/folders/1gwe0Bmq5m1V0oSGjCWDzPIlkqc7dqm3f', 'st' => 'https://drive.google.com/drive/folders/1rCgqberGLDSj9yn2McHVDc-0ydphqHRw', 'gd' => 'https://drive.google.com/drive/folders/1bd61AefAypTICA2PFfJw_5Ly3RCSRkqh', 'latest' => false],
            ['name' => 'MMI PRO NBT', 'system_version' => 'v3.3.5.mmipro.b', 'system_version_alt' => '3.3.5.mmipro.b', 'link' => 'https://drive.google.com/drive/folders/1gwe0Bmq5m1V0oSGjCWDzPIlkqc7dqm3f', 'st' => 'https://drive.google.com/drive/folders/1rCgqberGLDSj9yn2McHVDc-0ydphqHRw', 'gd' => 'https://drive.google.com/drive/folders/1bd61AefAypTICA2PFfJw_5Ly3RCSRkqh', 'latest' => false],
            ['name' => 'MMI PRO NBT', 'system_version' => 'v3.3.6.mmipro.b', 'system_version_alt' => '3.3.6.mmipro.b', 'link' => 'https://drive.google.com/drive/folders/1gwe0Bmq5m1V0oSGjCWDzPIlkqc7dqm3f', 'st' => 'https://drive.google.com/drive/folders/1rCgqberGLDSj9yn2McHVDc-0ydphqHRw', 'gd' => 'https://drive.google.com/drive/folders/1bd61AefAypTICA2PFfJw_5Ly3RCSRkqh', 'latest' => false],
            ['name' => 'MMI PRO NBT', 'system_version' => 'v3.3.7.mmipro.b', 'system_version_alt' => '3.3.7.mmipro.b', 'link' => 'https://drive.google.com/drive/folders/1gwe0Bmq5m1V0oSGjCWDzPIlkqc7dqm3f', 'st' => '', 'gd' => '', 'latest' => true],

            // ========== MMI PRO EVO (ST + GD) ==========
            ['name' => 'MMI PRO EVO', 'system_version' => 'v3.1.1.8R3.mmipro.e', 'system_version_alt' => '3.1.1.8R3.mmipro.e', 'link' => 'https://drive.google.com/drive/folders/1Mx1ysAA6_CL8Cx0dva4BSaiT_Bgsypb3', 'st' => 'https://drive.google.com/drive/folders/1qsKnjRagUMDDJac6ek4rHwYmKEDOlxB7', 'gd' => 'https://drive.google.com/drive/folders/1y2YKwsdAn9hllyBqcR_jPXIZh1CWuP1w', 'latest' => false],
            ['name' => 'MMI PRO EVO', 'system_version' => 'v3.1.1.8R4.mmipro.e', 'system_version_alt' => '3.1.1.8R4.mmipro.e', 'link' => 'https://drive.google.com/drive/folders/1Mx1ysAA6_CL8Cx0dva4BSaiT_Bgsypb3', 'st' => 'https://drive.google.com/drive/folders/1qsKnjRagUMDDJac6ek4rHwYmKEDOlxB7', 'gd' => 'https://drive.google.com/drive/folders/1y2YKwsdAn9hllyBqcR_jPXIZh1CWuP1w', 'latest' => false],
            ['name' => 'MMI PRO EVO', 'system_version' => 'v3.1.1.8R1.mmipro.e', 'system_version_alt' => '3.1.1.8R1.mmipro.e', 'link' => 'https://drive.google.com/drive/folders/1Mx1ysAA6_CL8Cx0dva4BSaiT_Bgsypb3', 'st' => 'https://drive.google.com/drive/folders/1qsKnjRagUMDDJac6ek4rHwYmKEDOlxB7', 'gd' => 'https://drive.google.com/drive/folders/1y2YKwsdAn9hllyBqcR_jPXIZh1CWuP1w', 'latest' => false],
            ['name' => 'MMI PRO EVO', 'system_version' => 'v3.1.1.9.mmipro.e', 'system_version_alt' => '3.1.1.9.mmipro.e', 'link' => 'https://drive.google.com/drive/folders/1Mx1ysAA6_CL8Cx0dva4BSaiT_Bgsypb3', 'st' => 'https://drive.google.com/drive/folders/1qsKnjRagUMDDJac6ek4rHwYmKEDOlxB7', 'gd' => 'https://drive.google.com/drive/folders/1y2YKwsdAn9hllyBqcR_jPXIZh1CWuP1w', 'latest' => false],
            ['name' => 'MMI PRO EVO', 'system_version' => 'v3.2.0.mmipro.e', 'system_version_alt' => '3.2.0.mmipro.e', 'link' => 'https://drive.google.com/drive/folders/1Mx1ysAA6_CL8Cx0dva4BSaiT_Bgsypb3', 'st' => 'https://drive.google.com/drive/folders/1qsKnjRagUMDDJac6ek4rHwYmKEDOlxB7', 'gd' => 'https://drive.google.com/drive/folders/1y2YKwsdAn9hllyBqcR_jPXIZh1CWuP1w', 'latest' => false],
            ['name' => 'MMI PRO EVO', 'system_version' => 'v3.3.0.mmipro.e', 'system_version_alt' => '3.3.0.mmipro.e', 'link' => 'https://drive.google.com/drive/folders/1Mx1ysAA6_CL8Cx0dva4BSaiT_Bgsypb3', 'st' => 'https://drive.google.com/drive/folders/1qsKnjRagUMDDJac6ek4rHwYmKEDOlxB7', 'gd' => 'https://drive.google.com/drive/folders/1y2YKwsdAn9hllyBqcR_jPXIZh1CWuP1w', 'latest' => false],
            ['name' => 'MMI PRO EVO', 'system_version' => 'v3.3.1.mmipro.e', 'system_version_alt' => '3.3.1.mmipro.e', 'link' => 'https://drive.google.com/drive/folders/1Mx1ysAA6_CL8Cx0dva4BSaiT_Bgsypb3', 'st' => 'https://drive.google.com/drive/folders/1qsKnjRagUMDDJac6ek4rHwYmKEDOlxB7', 'gd' => 'https://drive.google.com/drive/folders/1y2YKwsdAn9hllyBqcR_jPXIZh1CWuP1w', 'latest' => false],
            ['name' => 'MMI PRO EVO', 'system_version' => 'v3.3.2.mmipro.e', 'system_version_alt' => '3.3.2.mmipro.e', 'link' => 'https://drive.google.com/drive/folders/1Mx1ysAA6_CL8Cx0dva4BSaiT_Bgsypb3', 'st' => 'https://drive.google.com/drive/folders/1qsKnjRagUMDDJac6ek4rHwYmKEDOlxB7', 'gd' => 'https://drive.google.com/drive/folders/1y2YKwsdAn9hllyBqcR_jPXIZh1CWuP1w', 'latest' => false],
            ['name' => 'MMI PRO EVO', 'system_version' => 'v3.3.3.mmipro.e', 'system_version_alt' => '3.3.3.mmipro.e', 'link' => 'https://drive.google.com/drive/folders/1Mx1ysAA6_CL8Cx0dva4BSaiT_Bgsypb3', 'st' => 'https://drive.google.com/drive/folders/1qsKnjRagUMDDJac6ek4rHwYmKEDOlxB7', 'gd' => 'https://drive.google.com/drive/folders/1y2YKwsdAn9hllyBqcR_jPXIZh1CWuP1w', 'latest' => false],
            ['name' => 'MMI PRO EVO', 'system_version' => 'v3.3.4.mmipro.e', 'system_version_alt' => '3.3.4.mmipro.e', 'link' => 'https://drive.google.com/drive/folders/1Mx1ysAA6_CL8Cx0dva4BSaiT_Bgsypb3', 'st' => 'https://drive.google.com/drive/folders/1qsKnjRagUMDDJac6ek4rHwYmKEDOlxB7', 'gd' => 'https://drive.google.com/drive/folders/1y2YKwsdAn9hllyBqcR_jPXIZh1CWuP1w', 'latest' => false],
            ['name' => 'MMI PRO EVO', 'system_version' => 'v3.3.5.mmipro.e', 'system_version_alt' => '3.3.5.mmipro.e', 'link' => 'https://drive.google.com/drive/folders/1Mx1ysAA6_CL8Cx0dva4BSaiT_Bgsypb3', 'st' => 'https://drive.google.com/drive/folders/1qsKnjRagUMDDJac6ek4rHwYmKEDOlxB7', 'gd' => 'https://drive.google.com/drive/folders/1y2YKwsdAn9hllyBqcR_jPXIZh1CWuP1w', 'latest' => false],
            ['name' => 'MMI PRO EVO', 'system_version' => 'v3.3.6.mmipro.e', 'system_version_alt' => '3.3.6.mmipro.e', 'link' => 'https://drive.google.com/drive/folders/1Mx1ysAA6_CL8Cx0dva4BSaiT_Bgsypb3', 'st' => 'https://drive.google.com/drive/folders/1qsKnjRagUMDDJac6ek4rHwYmKEDOlxB7', 'gd' => 'https://drive.google.com/drive/folders/1y2YKwsdAn9hllyBqcR_jPXIZh1CWuP1w', 'latest' => false],
            ['name' => 'MMI PRO EVO', 'system_version' => 'v3.3.7.mmipro.e', 'system_version_alt' => '3.3.7.mmipro.e', 'link' => 'https://drive.google.com/drive/folders/1Mx1ysAA6_CL8Cx0dva4BSaiT_Bgsypb3', 'st' => '', 'gd' => '', 'latest' => true],

            // ========== LCI MMI Prime CIC (ST only) ==========
            ['name' => 'LCI MMI Prime CIC', 'system_version' => 'v3.4.1.mmiprixu.b', 'system_version_alt' => '3.4.1.mmiprixu.b', 'link' => '', 'st' => 'https://drive.google.com/drive/folders/1Hl3h1Az7vYzCiUO9RD8x6mvbF_pFAqJS', 'gd' => '', 'latest' => false],
            ['name' => 'LCI MMI Prime CIC', 'system_version' => 'v3.4.2.mmiprilci', 'system_version_alt' => '3.4.2.mmiprilci', 'link' => '', 'st' => 'https://drive.google.com/drive/folders/1Hl3h1Az7vYzCiUO9RD8x6mvbF_pFAqJS', 'gd' => '', 'latest' => false],
            ['name' => 'LCI MMI Prime CIC', 'system_version' => 'v3.4.4.mmiprilci', 'system_version_alt' => '3.4.4.mmiprilci', 'link' => '', 'st' => '', 'gd' => '', 'latest' => true],

            // ========== LCI MMI Prime NBT (GD only) ==========
            ['name' => 'LCI MMI Prime NBT', 'system_version' => 'v3.4.1.mmiprixu.b', 'system_version_alt' => '3.4.1.mmiprixu.b', 'link' => '', 'st' => '', 'gd' => 'https://drive.google.com/drive/folders/1y7pX-EiPzHtV9x29VregYmu8F9q6IGsG', 'latest' => false],
            ['name' => 'LCI MMI Prime NBT', 'system_version' => 'v3.4.2.mmiprilci', 'system_version_alt' => '3.4.2.mmiprilci', 'link' => '', 'st' => '', 'gd' => 'https://drive.google.com/drive/folders/1y7pX-EiPzHtV9x29VregYmu8F9q6IGsG', 'latest' => false],
            ['name' => 'LCI MMI Prime NBT', 'system_version' => 'v3.4.4.mmiprilci', 'system_version_alt' => '3.4.4.mmiprilci', 'link' => '', 'st' => '', 'gd' => '', 'latest' => true],

            // ========== LCI MMI Prime EVO (GD only) ==========
            ['name' => 'LCI MMI Prime EVO', 'system_version' => 'v3.4.1.mmiprixu.b', 'system_version_alt' => '3.4.1.mmiprixu.b', 'link' => '', 'st' => '', 'gd' => 'https://drive.google.com/drive/folders/1cG7ECeagNhRDC0VybI-nkjW7MGxxqMDQ', 'latest' => false],
            ['name' => 'LCI MMI Prime EVO', 'system_version' => 'v3.4.2.mmiprilci', 'system_version_alt' => '3.4.2.mmiprilci', 'link' => '', 'st' => '', 'gd' => 'https://drive.google.com/drive/folders/1cG7ECeagNhRDC0VybI-nkjW7MGxxqMDQ', 'latest' => false],
            ['name' => 'LCI MMI Prime EVO', 'system_version' => 'v3.4.4.mmiprilci', 'system_version_alt' => '3.4.4.mmiprilci', 'link' => '', 'st' => '', 'gd' => '', 'latest' => true],

            // ========== LCI MMI PRO CIC (ST only) ==========
            ['name' => 'LCI MMI PRO CIC', 'system_version' => 'v3.4.1.mmiproxu.b', 'system_version_alt' => '3.4.1.mmiproxu.b', 'link' => '', 'st' => 'https://drive.google.com/drive/folders/10QQWbjgQg_Gt5vZruZzJkeU_9qYg8YYn', 'gd' => '', 'latest' => false],
            ['name' => 'LCI MMI PRO CIC', 'system_version' => 'v3.4.2.mmiprolci', 'system_version_alt' => '3.4.2.mmiprolci', 'link' => '', 'st' => 'https://drive.google.com/drive/folders/10QQWbjgQg_Gt5vZruZzJkeU_9qYg8YYn', 'gd' => '', 'latest' => false],
            ['name' => 'LCI MMI PRO CIC', 'system_version' => 'v3.4.4.mmiprolci', 'system_version_alt' => '3.4.4.mmiprolci', 'link' => '', 'st' => '', 'gd' => '', 'latest' => true],

            // ========== LCI MMI PRO NBT (GD only) ==========
            ['name' => 'LCI MMI PRO NBT', 'system_version' => 'v3.4.1.mmiproxu.b', 'system_version_alt' => '3.4.1.mmiproxu.b', 'link' => '', 'st' => '', 'gd' => 'https://drive.google.com/drive/folders/1vaffOAawGnKXnkEKcA6d39JhtOTLwfJV', 'latest' => false],
            ['name' => 'LCI MMI PRO NBT', 'system_version' => 'v3.4.2.mmiprolci', 'system_version_alt' => '3.4.2.mmiprolci', 'link' => '', 'st' => '', 'gd' => 'https://drive.google.com/drive/folders/1vaffOAawGnKXnkEKcA6d39JhtOTLwfJV', 'latest' => false],
            ['name' => 'LCI MMI PRO NBT', 'system_version' => 'v3.4.4.mmiprolci', 'system_version_alt' => '3.4.4.mmiprolci', 'link' => '', 'st' => '', 'gd' => '', 'latest' => true],

            // ========== LCI MMI PRO EVO (GD only) ==========
            ['name' => 'LCI MMI PRO EVO', 'system_version' => 'v3.4.1.mmiproxu.b', 'system_version_alt' => '3.4.1.mmiproxu.b', 'link' => '', 'st' => '', 'gd' => 'https://drive.google.com/drive/folders/1Xgj1DXUHMbQON6Sm_wYB76H04HkYBNHV', 'latest' => false],
            ['name' => 'LCI MMI PRO EVO', 'system_version' => 'v3.4.2.mmiprolci', 'system_version_alt' => '3.4.2.mmiprolci', 'link' => '', 'st' => '', 'gd' => 'https://drive.google.com/drive/folders/1Xgj1DXUHMbQON6Sm_wYB76H04HkYBNHV', 'latest' => false],
            ['name' => 'LCI MMI PRO EVO', 'system_version' => 'v3.4.4.mmiprolci', 'system_version_alt' => '3.4.4.mmiprolci', 'link' => '', 'st' => '', 'gd' => '', 'latest' => true],
        ];
    }
}
